### ISSUE TITLE
Final steps before CTAN submission

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/latex-response-reviewers#5]
The initial version of this template looks great, and we can start thinking about submitting this to CTAN.

@KukovecRok, what do you think? What are the issues that need further examination before we proceed?

**Comment by KukovecRok** [comment]
Code looks well, maybe it makes sense to update the date in '\ProvidesClass{jourrr}[2023/05/16 Response to reviewers template]'. I can do that just before submission. Any other comments / observations on what to fix before submission @firefly-cpp ?

**Comment by firefly-cpp** [comment]
Yes, @KukovecRok.

**Comment by firefly-cpp** [comment]
No more comments

**Comment by firefly-cpp** [comment]
Maybe we can try to update "features" section in README with all functionalities.

**Comment by KukovecRok** [comment]
okay, I will update README and date, push submission to CTAN and then mark this issue as completed.
