### ISSUE TITLE
Allow also manual Referee counter

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/latex-response-reviewers#6]
Sometimes the reviewers' ids are not in order, especially in cases where someone does not agree to do a review.

A simple scenario (reviewer two is missing):

# Reviewer 1

# Reviewer 3

In our class, we should provide the support that can manually include the ids of reviewers.

**Comment by KukovecRok** [comment]
Instead of manual setting of ID's, I've added phantom counter increment in b931783 . Since Reviewers probably never will go in descending / random order, but only ascending with possible missing ID's. 
If that is not okay, I can add an option to manually set ID.

**Comment by KukovecRok** [comment]
@firefly-cpp Please review commit b931783 and close issue if applicable

**Comment by firefly-cpp** [comment]
Thanks!
