### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by firefly-cpp** [firefly-cpp/latex-response-reviewers#7]
The current template does not show tables in responses.

**Comment by firefly-cpp** [comment]
@KukovecRok

**Comment by KukovecRok** [comment]
Added in commit 6806a57

**Comment by KukovecRok** [comment]
@firefly-cpp If I understand correctly, you want to be able to add a table as a response?

**Comment by firefly-cpp** [comment]
@KukovecRok, yes.

**Comment by KukovecRok** [comment]
@firefly-cpp Should we mark this as closed?

**Comment by firefly-cpp** [comment]
Yes.
